update github workflow

diff --git a/.github/workflows/lidar_validate.yml b/.github/workflows/lidar_validate.yml
--- a/.github/workflows/lidar_validate.yml
+++ b/.github/workflows/lidar_validate.yml
@@ -12,6 +12,12 @@ jobs:
   validate:
     runs-on: ubuntu-latest
     steps:
+    - name: Verify COPC URL
+      run: |
+        if [[ ! "${{ github.event.inputs.copc_url }}" =~ \.copc\.laz$ ]]; then
+          echo "Error: Provided URL does not end with .copc.laz"
+          exit 1
+        fi
     - name: Checkout repo
       uses: actions/checkout@v4
 
@@ -25,10 +31,12 @@ jobs:
 
     - name: Download COPC file
       run: |
-        wget --retry-connrefused --waitretry=5 --timeout=30 --tries=5 "${{ github.event.inputs.copc_url }}" -O input.copc.laz
+        wget --quiet --retry-connrefused --waitretry=5 --timeout=30 --tries=5 "${{ github.event.inputs.copc_url }}" -O input.copc.laz
 
     - name: Run validation script
       run: |
+        source "$HOME/miniconda3/etc/profile.d/conda.sh"
+        conda activate lidar-env
         python check_impulsions.py input.copc.laz
 
     - name: Upload CSV artifacts
